export const LOAD_APPLICATIONS_START = "LOAD_APPLICATIONS_START";
export const LOAD_APPLICATIONS_SUCCESS = "LOAD_APPLICATIONS_SUCCESS";

export const LOAD_TEST_SUCCESS = "LOAD_TEST_SUCCESS";
export const LOAD_TEST_START = "LOAD_TEST_START";